// Generated by CoffeeScript 1.4.0
(function() {
  var Css, Js, expect, fs, helper;

  expect = require('expect.js');

  Js = require('./../lib/js');

  Css = require('./../lib/css');

  helper = require('./helper');

  fs = require('fs');

  describe('When adding JS Object', function() {
    beforeEach(function() {
      helper.beforeEach();
      this.js = new Js({
        staticRoot: "" + __dirname + "/files/public",
        staticUrlRoot: '/'
      });
      return this.css = new Css({
        staticRoot: "" + __dirname + "/files/public",
        staticUrlRoot: '/'
      });
    });
    return it('should add the correct paths when adding an URL', function() {
      var file;
      this.js.addObject({
        'MyApp.env': {}
      });
      file = this.js.files[0];
      expect(file.url).to.eql({});
      return expect(file.file).to.eql({
        'MyApp.env': {}
      });
    });
  });

}).call(this);
