// Generated by CoffeeScript 1.4.0
(function() {
  var AssetsManager,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  AssetsManager = (function() {

    function AssetsManager(css, js) {
      this.css = css;
      this.js = js;
      this.addJsObject = __bind(this.addJsObject, this);

      this.addJsUrl = __bind(this.addJsUrl, this);

      this.addJs = __bind(this.addJs, this);

      this.addCssUrl = __bind(this.addCssUrl, this);

      this.addCss = __bind(this.addCss, this);

      this.root = '';
    }

    AssetsManager.prototype.addCss = function(file, namespace) {
      if (namespace == null) {
        namespace = void 0;
      }
      return this.css.addFile("" + this.root + "/" + file, namespace);
    };

    AssetsManager.prototype.addCssUrl = function(file, namespace) {
      if (namespace == null) {
        namespace = void 0;
      }
      return this.css.addUrl(file, namespace);
    };

    AssetsManager.prototype.addJs = function(file, namespace) {
      if (namespace == null) {
        namespace = void 0;
      }
      return this.js.addFile("" + this.root + "/" + file, namespace);
    };

    AssetsManager.prototype.addJsUrl = function(file, namespace) {
      if (namespace == null) {
        namespace = void 0;
      }
      return this.js.addUrl(file, namespace);
    };

    AssetsManager.prototype.addJsObject = function(obj, namespace) {
      if (namespace == null) {
        namespace = void 0;
      }
      return this.js.addObject(obj, namespace);
    };

    return AssetsManager;

  })();

  module.exports = AssetsManager;

}).call(this);
