// Generated by CoffeeScript 1.4.0
(function() {
  var compile, fs;

  fs = require('fs');

  exports.compile = compile = function(compilers, content, file, cb) {
    var fileExt;
    fileExt = file.split('.');
    fileExt = fileExt[fileExt.length - 1];
    switch (fileExt) {
      case 'coffee':
        try {
          return cb(null, compilers.coffee(content, file));
        } catch (err) {
          console.log(file + ':\n  ' + err.message + "\n");
          return cb(err, err.message);
        }
        break;
      case 'styl':
        return compilers.stylus(content, file).render(function(err, css) {
          if (err != null) {
            console.log(err.message);
            css = err.message;
          }
          return cb(err, css);
        });
      case 'css':
        return cb(null, compilers.css(content));
      case 'js':
        return cb(null, compilers.js(content));
    }
  };

  exports.compileFile = function(compilers, file, cb) {
    var content;
    content = fs.readFileSync(file, 'utf-8');
    return compile(compilers, content, file, cb);
  };

}).call(this);
