// Generated by CoffeeScript 1.4.0
(function() {
  var coffee, stylus;

  coffee = require('coffee-script');

  stylus = require('stylus');

  module.exports = {
    stylus: function(content, file) {
      return stylus(content).set('filename', file);
    },
    coffee: function(content, file) {
      return coffee.compile(content);
    },
    js: function(content) {
      return content;
    },
    css: function(content) {
      return content;
    }
  };

}).call(this);
