// Generated by CoffeeScript 1.4.0
(function() {
  var fs, mkdirp, normalizeUrl, writeToFile;

  mkdirp = require('mkdirp');

  fs = require('fs');

  writeToFile = function(file, content) {
    var splitted;
    try {
      return fs.writeFileSync(file, content);
    } catch (e) {
      if (e.code === 'ENOENT' || e.code === 'EBADF') {
        splitted = file.split('/');
        mkdirp.sync(splitted.splice(0, splitted.length - 1).join('/'), 0x1ff);
        return writeToFile(file, content);
      } else {
        return console.log(e);
      }
    }
  };

  normalizeUrl = function(url) {
    var protocol, _ref;
    protocol = (_ref = url.match(/^(http|https):\/\//)) != null ? _ref[0] : void 0;
    if (protocol == null) {
      protocol = '';
    }
    url = url.replace(protocol, '');
    url = url.replace('\\', '/');
    url = url.replace('//', '/');
    return protocol + url;
  };

  exports.writeToFile = writeToFile;

  exports.normalizeUrl = normalizeUrl;

  exports.fileExistSync = function(filePath) {
    try {
      fs.statSync(filePath);
    } catch (err) {
      if (err.code === 'ENOENT') {
        return false;
      }
    }
    return true;
  };

}).call(this);
